### ISSUE TITLE
Changing time on 1st HW slot

### ISSUE THREAD

**Issue by jazzmccrack** [roadsnail/Pi-ve#3]
Morning, i have the hot water only come on from half 7 to 8 am daily. I have deleted all the time slots except the first, but when i edit that time slot to the times i want it never saves and i have to edit the Pive-HW file directly and it works.

**Comment by roadsnail** [comment]
Hi. Which version of the node-red flow are you running? (The version is shown top left of the pi-ve dashboard). 

I have deleted all HW time slots for a day except for the first- then edited that time slot and it appears to save correctly... I have tested with version 2-14Beta at https://github.com/roadsnail/Pi-ve/blob/main/Pi-ve%20flow%20v2-14beta

**Comment by jazzmccrack** [comment]
Im on beta 2.14

If i add another slot, it wont let me change the times either.

Tried with the CH side also and no dice.

Thanks for reply, love the work.

**Comment by roadsnail** [comment]
> Im on beta 2.14

That's good. I saw the problem you describe on V1.xx of the flow. But as I mentioned V2.14 works as expected for me... Odd. 
> 
> If i add another slot, it wont let me change the times either.
Okay. Thanks for the additional info. There again that should work and does for me. Still odd!
> 
> Tried with the CH side also and no dice.

See above..
> 
> Thanks for reply, love the work.

No problem and thanks. Happy to help if I can.

I'll take another look as soon as possible as I'm busy with other stuff currently. I'm presuming you are running this on a Rpi and have checked node-red plus nodes are reasonably up to date? I'll do the same as maybe I'm running an older version of NR.

Also, has it worked previously and stopped working or is this a new install?
