### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by mr-lewlew** [roadsnail/Pi-ve#4]
Hi I was wondering if you have a step by step install guide.

I was also wondering if the timing schedule setup via your web server saves data to the hive unit itself?

**Comment by roadsnail** [comment]
Hi,

Install guide (for installing on a Rpi Zero W) at https://github.com/roadsnail/Pi-ve#readme

The timing schedule is not stored in the Hive controller. It is stored as a file in two files stored within the Rpi's node-red environment. They are named Pive-CH and Pive-HW and stored, (if installed by user pi), in /home/pi

example contents of Pive-HW ...

$ cat Pive-HW
[["Sun",[{"startTime":480,"endTime":540},{"startTime":600,"endTime":660},{"startTime":720,"endTime":780},{"startTime":840,"endTime":900},{"startTime":960,"endTime":1020},{"startTime":1080,"endTime":1140},{"startTime":1200,"endTime":1260},{"startTime":1320,"endTime":1380}]],["Mon",[{"startTime":480,"endTime":540},{"startTime":600,"endTime":660},{"startTime":720,"endTime":780},{"startTime":840,"endTime":900},{"startTime":960,"endTime":1020},{"startTime":1080,"endTime":1140},{"startTime":1200,"endTime":1260},{"startTime":1320,"endTime":1380}]],["Tue",[{"startTime":480,"endTime":540},{"startTime":600,"endTime":660},{"startTime":720,"endTime":780},{"startTime":840,"endTime":900},{"startTime":960,"endTime":1020},{"startTime":1080,"endTime":1140},{"startTime":1200,"endTime":1260},{"startTime":1320,"endTime":1380}]],["Wed",[{"startTime":480,"endTime":540},{"startTime":600,"endTime":660},{"startTime":720,"endTime":780},{"startTime":840,"endTime":900},{"startTime":960,"endTime":1020},{"startTime":1080,"endTime":1140},{"startTime":1200,"endTime":1260},{"startTime":1320,"endTime":1380}]],["Thu",[{"startTime":480,"endTime":540},{"startTime":600,"endTime":660},{"startTime":720,"endTime":780},{"startTime":840,"endTime":900},{"startTime":960,"endTime":1020},{"startTime":1080,"endTime":1140},{"startTime":1200,"endTime":1260},{"startTime":1320,"endTime":1380}]],["Fri",[{"startTime":480,"endTime":540},{"startTime":600,"endTime":660},{"startTime":720,"endTime":780},{"startTime":840,"endTime":900},{"startTime":960,"endTime":1020},{"startTime":1080,"endTime":1140},{"startTime":1200,"endTime":1260},{"startTime":1320,"endTime":1380}]],["Sat",[{"startTime":480,"endTime":540},{"startTime":600,"endTime":660},{"startTime":720,"endTime":780},{"startTime":840,"endTime":900},{"startTime":960,"endTime":1020},{"startTime":1080,"endTime":1140},{"startTime":1200,"endTime":1260},{"startTime":1320,"endTime":1380}]]]
