### ISSUE TITLE
Should the linux install instructions work for Raspberry Pi Zero 2?

### ISSUE THREAD

**Issue by davidhbone** [roadsnail/Pi-ve#5]
I have followed the instructions for Linux but I getting nowhere very slowly.  npm ci took 9 hours and was reporting "not ok"
Initially I want to know if this should be working (I may have done something wrong)

**Comment by roadsnail** [comment]
Hi. Sorry to hear you are having issues. My build used the RPi Zero as the ver. 2 wasn't out at the time. 

The npm ci should not take 9 hours. Probably about 15 or so mins from memory. But don't quote me.

If I get time over the hols, I'll try following the guide on a Pi Zero 2.

**Comment by davidhbone** [comment]
I was trying to use Raspian Bullseye with a Desktop so memory was probably a problem.  I reverted to Buster Lite (not sure if that was necessary) and an earlier version of Nodejs (16.9.0) as zigbee2mqtt was reported as having a problem with later versions (to be fixed in New Year).  I now have something to tinker with...

**Comment by roadsnail** [comment]
@davidhbone Good to hear you made some progress. I am currently working on a re-write of the node-red flows in this project to support the latest zigbee2mqtt release and support the native boost function of the newer Hive remotes. Still early days, but progress is being made.
