### ISSUE TITLE
Last seen

### ISSUE THREAD

**Issue by jackoboy9** [roadsnail/Pi-ve#6]
Last seen time not updating - it's 4 hours out of sync and counting. Pive has been working perfectly fine for 5 days.

**Comment by roadsnail** [comment]
Odd. If you take a look at the node-red flow, there is a MQTT 'get' of the Hive Controller that triggers every 1 minute.
This should get a response on the last_seen topic that refreshes the last update time.

By the way, I have a new version much modified flow that has the same functionality as the one here but also handles the native HW/CH boost switches located on the hive thermostat. When I get time, I will update with the latest node-red flow. This new flow also uses the latest zigbee2mqtt releases.

**Comment by jackoboy9** [comment]
Ah great. I think it might have been a glitch. I tried restarting both services, but that didn't work. Surprisingly, rebooting the Pi seems to have worked. 

Thanks for your hard work with this project. I look forward to your new node-red flow. Would you mind leaving instructions on how to upgrade?

**Comment by roadsnail** [comment]
Hi again... I'll try to get the flow uploaded ASAP. Bit busy at the moment with other stuff.  As for upgrading, I'll zap my installation then reload the version you are running, then carry out the upgrade on my setup. Hopefully that will throw up any issues.

Obviously as always, make sure you have a backup of your existing installation just in case you need to revert. If you are running it on a Pi from an SD card, then it should be a fairly quick process to backup the whole SD card, restore to a different card and boot from that card just to make sure your backup is good. Then if the worst comes to the worst you know you can get your existing system working again.
