### ISSUE TITLE
SLR without SLT

### ISSUE THREAD

**Issue by StickManMobile** [roadsnail/Pi-ve#7]
Have you managed to get it working when the SLT is switch off? Of I switch off my SLT and try to control the SLT it fails after a period of time with the SLR showing a red link light.

**Comment by roadsnail** [comment]
I haven't tried running the SLR without the SLT. But I guess both devices have some integration in their firmware that requires both to interact. 
I must get around to publishing my latest pi-ve flow when I find more time. It builds upon this revision to run on a newer zigbee2mqtt and also offers integration with the HW and CH boost function of the SLT.
